--LAB 5: THỰC HÀNH TẠI LỚP
-- CAU 2: QuanLyGiaoVu I.9 đến I.24

set dateformat dmy
GO

--9.
CREATE TRIGGER TG_CAU9 ON LOP
FOR INSERT
AS BEGIN
	DECLARE @TruongLop CHAR(5), @MaLop CHAR(3), @MaHV CHAR(5)
	SELECT @TruongLop =ins.TRGLOP ,@MaLop=ins.MALOP FROM inserted ins
	SELECT @MaHV=HV.MAHV FROM inserted ins, HOCVIEN HV WHERE HV.MALOP=ins.MALOP
	IF(@TruongLop = @MaHV) BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE BEGIN
		PRINT 'KHONG THEM DUOC'
		ROLLBACK TRAN
	END
END
GO
--10.	
CREATE TRIGGER TG_CAU10 ON KHOA
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @TruongKhoa	CHAR(4), @MaGV CHAR(4), @HocVi VARCHAR(10)
	SELECT @TruongKhoa=ins.TRGKHOA, @HocVi=GV.HOCVI FROM inserted ins, GIAOVIEN GV WHERE ins.TRGKHOA=GV.MAGV AND ins.MAKHOA=GV.MAKHOA
	IF(@HocVi IN ('TS','PTS')) BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE BEGIN
		PRINT 'KHONG THANH CONG'
		ROLLBACK TRAN
	END
END
GO
--11.
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_HOCVIEN_KTNGSINH CHECK ( YEAR(GETDATE()) - YEAR(NGSINH)>=18)

--12.
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_GIANGDAY_THOIGIANGD CHECK (TUNGAY < DENNGAY)

--13.
ALTER TABLE GIAOVIEN 
ADD CONSTRAINT CHK_GIAOVIEN_NGVL CHECK ( YEAR(NGVL) - YEAR(NGSINH) >=22)

--14.
ALTER TABLE MONHOC 
ADD CONSTRAINT CHK_MONHOC_CHENHLECH CHECK ( ABS(TCLT-TCTH) <=3 )
GO
--15.
CREATE TRIGGER TG__CAU15 ON HOCVIEN
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @MaLOP CHAR(3), @MaHV CHAR(5), @NgTHI SMALLDATETIME, @DenNGAY SMALLDATETIME
	SELECT @DenNGAY=GD.DENNGAY FROM inserted ins, GIANGDAY GD WHERE ins.MALOP=GD.MALOP
	SELECT @NgTHI=KQT.NGTHI FROM inserted ins, KETQUATHI KQT WHERE ins.MAHV=KQT.MAHV
	IF(@DenNGAY<=@NgTHI) BEGIN
		PRINT 'SUCCESSFUL'
	END
	ELSE BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
END
GO
--16.	
CREATE TRIGGER TG_CAU16 ON LOP
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @MaLop CHAR(3), @HocKy TINYINT
	SELECT @MaLop=ins.MALOP FROM inserted ins
	IF (3>= (SELECT COUNT(GD.MAMH) AS SL FROM LOP L, GIANGDAY GD WHERE L.MALOP=GD.MALOP GROUP BY  L.MALOP, GD.HOCKY))
	BEGIN PRINT 'SUCCESSFUL'
	END
	ELSE BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
END
GO
--17.	
CREATE TRIGGER TR_CAU17 ON LOP
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @SiSo TINYINT, @MaLOP CHAR(3)
	SELECT @SiSo=ins.SISO FROM inserted ins
	IF (@SiSo = (SELECT COUNT(HV.MALOP) FROM inserted ins, HOCVIEN HV WHERE ins.MALOP=HV.MALOP))
	BEGIN PRINT 'SUCCESSFUL'
	END
	ELSE BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
END
GO
--18.
CREATE TRIGGER TG_CAU18 ON DIEUKIEN
FOR INSERT, UPDATE
AS BEGIN
	IF( 0 <> (SELECT COUNT(*) FROM inserted ins WHERE (ins.MAMH=ins.MAMH_TRUOC) OR ((ins.MAMH=ins.MAMH_TRUOC) AND (ins.MAMH_TRUOC=ins.MAMH))))
	BEGIN 
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT('SUCCESSFUL')
	END
END
GO
--19.
CREATE TRIGGER TG_CAU19 ON GIAOVIEN
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @SL INT
	SELECT @SL=COUNT(*) FROM inserted ins, GIAOVIEN GV WHERE ins.HOCHAM=GV.HOCHAM AND ins.HOCVI=GV.HOCHAM AND ins.HESO=GV.HESO AND ins.MUCLUONG<>GV.MUCLUONG
	IF(@SL<>0) BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT 'SUCCESSFUL'
	END
END
GO
--20.	
CREATE TRIGGER TG_CAU20 ON KETQUATHI
FOR INSERT, UPDATE
AS BEGIN
    DECLARE @KT numeric(4,2)
    SELECT @KT = COUNT(*)
    FROM Inserted I, KETQUATHI KQ
    WHERE I.MAHV = KQ.MAHV AND I.MAMH = KQ.MAMH AND KQ.LANTHI = I.LANTHI - 1 AND KQ.DIEM >= 5
    IF (@KT <> 0) BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT 'SUCCESSFUL'
	END
END
GO
--21.
CREATE TRIGGER TG_CAU21 ON KETQUATHI
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @KT NUMERIC(4,2)
	SELECT @KT=COUNT(*)  FROM inserted ins, KETQUATHI KQT WHERE ins.LANTHI=KQT.LANTHI-1 AND ins.NGTHI>KQT.NGTHI
	IF(@KT<>0) BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT('SUCCESSFUL')
	END
END
GO
--22.	
CREATE TRIGGER TG_CAU22 ON KETQUATHI
FOR UPDATE, INSERT
AS 
	BEGIN
		DECLARE @MAMH char(10), @MAHV char(5), @MALOP char(3)
		SELECT @MAMH = MAMH, @MAHV = MAHV FROM inserted
		SELECT @MALOP = MALOP FROM HOCVIEN WHERE MAHV = @MAHV

		IF (select count(distinct KETQUATHI.MAHV) from KETQUATHI,HOCVIEN,LOP where KETQUATHI.MAHV=HOCVIEN.MAHV and HOCVIEN.MALOP=LOP.MALOP and  MAMH=@MAMH and LOP.MALOP = @MALOP)  
			< (select siso from LOP where MALOP = @MALOP)
			BEGIN
				PRINT('HOC VIEN CHI DUOC THI NHUNG MON MA LOP CUA HOC VIEN DO DA HOC XONG')
				ROLLBACK TRAN
			END
		ELSE PRINT('SUCCESSFUL')
	END	
GO
--23.	
CREATE TRIGGER TG_CAU23 ON GIANGDAY
FOR INSERT, UPDATE
AS BEGIN
	DECLARE @KT NUMERIC(4,2)
	SELECT @KT=COUNT(*) FROM inserted ins, GIAOVIEN GV, KHOA K
	WHERE ((ins.MAGV=gv.MAGV) AND (GV.MAKHOA=K.MAKHOA)) AND ins.MAMH <> (SELECT MH.MAMH FROM MONHOC MH WHERE MH.MAKHOA=K.MAKHOA)
	IF(@KT<>0) BEGIN
		PRINT('KHONG THANH CONG')
		ROLLBACK TRAN
	END
	ELSE BEGIN
		PRINT('SUCCESSFUL')
	END
END
GO

--24.
CREATE TRIGGER TG_CAU24 ON GIANGDAY
FOR INSERT, UPDATE
AS
	BEGIN
		DECLARE @MAGV char(4), @MAMH char(10), @MAKHOA char(4)
		SELECT @MAGV = MAGV, @MAMH = MAMH FROM inserted
		SELECT @MAKHOA = MAKHOA FROM GIAOVIEN WHERE MAGV = @MAGV

		IF @MAMH NOT IN (SELECT MAMH FROM MONHOC WHERE MAKHOA = @MAKHOA)
		BEGIN
			PRINT('GIAO VIEN CHI DUOC PHAN CONG DAY NHUNG MON THUOC KHOA GIAO VIEN DO PHU TRACH')
			ROLLBACK TRAN
		END
		ELSE PRINT('SUCCESSFUL')
	END
GO
