--LAB 5: THỰC HÀNH TẠI LỚP
-- CAU 1: QuanLyBanHang I.11 đến I.15

set dateformat dmy
GO
-- I.11
CREATE TRIGGER trg_NGHD_HOADON_C11
ON HOADON
FOR INSERT,UPDATE
AS 
	BEGIN
		DECLARE @NGHD smalldatetime, @MAKH char(4)
		SELECT @NGHD = NGHD, @MAKH = MAKH FROM inserted

		IF (@MAKH IS NOT NULL)
			BEGIN
				IF @NGHD< (SELECT NGDK FROM KHACHHANG WHERE MAKH = @MAKH)
					BEGIN
						PRINT(N'NGÀY MUA HÀNG PHẢI LỚN HƠN HOẶC BẰNG NGÀY KHÁCH HÀNG ĐĂNG KÝ THÀNH VIÊN')
						ROLLBACK TRANSACTION
					END
				ELSE PRINT('SUCCESSFUL')
			END
	END
GO

CREATE TRIGGER trg_NGDK_KHACHHANG_C11
ON KHACHHANG
FOR UPDATE
AS
	BEGIN
		DECLARE @NGDK smalldatetime, @MAKH char(4)
		SELECT @NGDK = NGDK, @MAKH = MAKH FROM inserted

		IF @NGDK > ANY (SELECT NGHD FROM HOADON WHERE MAKH=@MAKH)
			BEGIN 
				PRINT(N'NGÀY ĐĂNG KÝ THÀNH VIÊN KHÔNG ĐƯỢC LỚN HƠN NGÀY MUA HÀNG')
				ROLLBACK TRANSACTION
			END
		ELSE PRINT('SUCCESSFULL')
	END
GO

-- I.12
CREATE TRIGGER trg_NGHD_HOADON_C12
ON HOADON
FOR INSERT,UPDATE
AS 
	BEGIN
		DECLARE @NGHD smalldatetime, @MANV char(4)
		SELECT @NGHD = NGHD, @MANV = MANV FROM inserted

		IF @NGHD< (SELECT NGVL FROM NHANVIEN WHERE MANV = @MANV)
					BEGIN
						PRINT(N'NGÀY BÁN HÀNG CỦA NHÂN VIÊN PHẢI LỚN HƠN HOẶC BẰNG NGÀY NHÂN VIÊN VÀO LÀM')
						ROLLBACK TRANSACTION
					END
		ELSE PRINT('SUCCESSFUL')	
	END
GO

CREATE TRIGGER trg_NGVL_NHANVIEN_C12
ON NHANVIEN
FOR UPDATE
AS 
	BEGIN
		DECLARE @NGVL smalldatetime, @MANV char(4)
		SELECT @NGVL = NGVL, @MANV = MANV FROM inserted

		IF @NGVL > ANY (SELECT NGHD FROM HOADON WHERE MANV = @MANV)
					BEGIN
						PRINT(N'NGÀY NHÂN VIÊN VÀO LÀM KHÔNG ĐƯỢC LỚN HƠN NGÀY BÁN HÀNG CỦA NHÂN VIÊN ĐÓ')
						ROLLBACK TRANSACTION
					END
		ELSE PRINT('SUCCESSFUL')	
	END
GO

-- I.13
CREATE TRIGGER trg_HOADON_C13
ON HOADON
FOR INSERT
AS 
	BEGIN
		DECLARE @SOHD int
		SELECT @SOHD = SOHD FROM inserted

		INSERT INTO CTHD VALUES (@SOHD,'NONE',0)
		PRINT(N'ĐÃ THÊM THÀNH CÔNG HÓA ĐƠN, ĐỀ NGHỊ UPDATE LẠI CTHD CỦA HÓA ĐƠN NÀY (MẶC ĐỊNH: MASP = "NONE", SL = 0')
	END

GO

CREATE TRIGGER trg_CTHD_UPDATE_C13
ON CTHD
FOR UPDATE,DELETE
AS
	BEGIN
		DECLARE @SOHD int, @SLCTHD int
		SELECT @SOHD = SOHD FROM deleted
		SELECT @SLCTHD =  COUNT(SOHD) FROM CTHD WHERE SOHD = @SOHD

		IF @SLCTHD<1
			BEGIN
				PRINT('SO LUONG CHI TIET HOA DON CUA MOI HOA DON PHAI LON HON HOAC BANG 1')
				ROLLBACK TRANSACTION
			END
		ELSE PRINT('SUCCESSFUL')
	END
GO

-- I.14
CREATE TRIGGER trg_CTHD_INSERT_C14
ON CTHD
FOR INSERT
AS
	BEGIN
		DECLARE @SOHD int, @GIA money, @SL INT
		SELECT @SOHD = SOHD, @SL = SL FROM inserted
		SELECT @GIA = GIA FROM SANPHAM, inserted WHERE SANPHAM.MASP = inserted.MASP

		UPDATE HOADON
		SET TRIGIA = TRIGIA + @SL*@GIA
		WHERE SOHD=@SOHD
		PRINT('SUCCESSFUL')
	END
GO

CREATE TRIGGER trg_CTHD_DELETE_C14
ON CTHD
FOR DELETE
AS
	BEGIN
		DECLARE @SOHD int, @GIA money, @SL INT
		SELECT @SOHD = SOHD, @SL = SL FROM deleted
		SELECT @GIA = GIA FROM SANPHAM, deleted WHERE SANPHAM.MASP = deleted.MASP

		UPDATE HOADON
		SET TRIGIA = TRIGIA - @SL*@GIA
		WHERE SOHD=@SOHD
		PRINT('SUCCESSFUL')
	END
GO

CREATE TRIGGER trg_CTHD_UPDATE_C14
ON CTHD
FOR UPDATE
AS
	BEGIN
		DECLARE @SOHD_IN int, @GIA_IN money, @SL_IN INT
		DECLARE @SOHD_DE int, @GIA_DE money, @SL_DE INT

		SELECT @SOHD_IN = SOHD, @SL_IN = SL FROM inserted
		SELECT @GIA_IN = GIA FROM SANPHAM, inserted WHERE SANPHAM.MASP = inserted.MASP

		SELECT @SOHD_DE = SOHD, @SL_DE = SL FROM deleted
		SELECT @GIA_DE = GIA FROM SANPHAM, deleted WHERE SANPHAM.MASP = deleted.MASP

		UPDATE HOADON
		SET TRIGIA = TRIGIA+@SL_IN*@GIA_IN
		WHERE SOHD = @SOHD_IN

		UPDATE HOADON
		SET TRIGIA = TRIGIA - @SL_DE*@GIA_DE
		WHERE SOHD = @SOHD_DE

		PRINT('SUCCESSFUL')
	END
GO

-- I.15
CREATE TRIGGER TRG_HOADON_INSERT_C15
ON HOADON
FOR INSERT
AS
	BEGIN
		DECLARE @MAKH char(4), @TRIGIA  money
		SELECT @MAKH = MAKH, @TRIGIA = TRIGIA  FROM inserted

		UPDATE KHACHHANG
		SET DOANHSO = DOANHSO + @TRIGIA
		WHERE MAKH = @MAKH

		PRINT('SUCCESSFUL')
	END
GO

CREATE TRIGGER TRG_HOADON_DELETE_C15
ON HOADON
FOR DELETE
AS
	BEGIN
		DECLARE @MAKH char(4), @TRIGIA  money
		SELECT @MAKH = MAKH, @TRIGIA = TRIGIA  FROM deleted

		UPDATE KHACHHANG
		SET DOANHSO = DOANHSO - @TRIGIA
		WHERE MAKH = @MAKH

		PRINT('SUCCESSFUL')
	END
GO

CREATE TRIGGER TRG_HOADON_UDATE_C15
ON HOADON
FOR UPDATE
AS
	BEGIN
		DECLARE @MAKH_IN char(4), @TRIGIA_IN  money
		DECLARE @MAKH_DE char(4), @TRIGIA_DE  money
		SELECT @MAKH_IN = MAKH, @TRIGIA_IN = TRIGIA  FROM inserted
		SELECT @MAKH_DE = MAKH, @TRIGIA_DE = TRIGIA  FROM deleted

		UPDATE KHACHHANG
		SET DOANHSO = DOANHSO + @TRIGIA_IN
		WHERE MAKH = @MAKH_IN

		UPDATE KHACHHANG
		SET DOANHSO = DOANHSO - @TRIGIA_DE
		WHERE MAKH = @MAKH_DE

		PRINT('SUCCESSFUL')
	END
GO