CREATE TABLE DOCGIA
(
	MA_DOCGIA NUMBER PRIMARY KEY,
	HO VARCHAR2(15),
	TENLOT VARCHAR2(1),
	TEN VARCHAR2(15),
	NGAYSINH DATE
);

CREATE TABLE NGUOILON
(
	MA_DOCGIA NUMBER PRIMARY KEY,
	SONHA NVARCHAR2(15),
	DUONG NVARCHAR2(63),
	QUAN NVARCHAR2(2),
	DIENTHOAI NVARCHAR2(13),
	HAN_SD DATE,
	CONSTRAINT FK_NGUOILON_DOCGIA FOREIGN KEY (MA_DOCGIA) REFERENCES DOCGIA(MA_DOCGIA)
);

CREATE TABLE TREEM
(
	MA_DOCGIA NUMBER PRIMARY KEY,
	MA_DOCGIA_NGUOILON NUMBER,
	CONSTRAINT FK_TREEM_NGUOILON FOREIGN KEY (MA_DOCGIA_NGUOILON) REFERENCES NGUOILON(MA_DOCGIA),
	CONSTRAINT FK_TREEM_DOCGIA FOREIGN KEY (MA_DOCGIA) REFERENCES DOCGIA(MA_DOCGIA)
);

CREATE TABLE TUASACH
(
	MA_TUASACH NUMBER PRIMARY KEY,
	TUASACH NVARCHAR2(63),
	TACGIA NVARCHAR2(31),
	TOMTAT NVARCHAR2(222)
);

CREATE TABLE DAUSACH
(
	ISBN NUMBER PRIMARY KEY,
	MA_TUASACH NUMBER,
	NGONNGU NVARCHAR2(15),
	BIA NVARCHAR2(15),
	TRANGTHAI NVARCHAR2(1),
	CONSTRAINT FK_DAUSACH_TUASACH FOREIGN KEY (MA_TUASACH) REFERENCES TUASACH(MA_TUASACH)
);

CREATE TABLE CUONSACH
(
	ISBN NUMBER,
	MA_CUONSACH NUMBER,
	TINHTRANG NVARCHAR2(1),
	CONSTRAINT PK_CS PRIMARY KEY(ISBN,MA_CUONSACH),
	CONSTRAINT FK_CUONSACH_DAUSACH FOREIGN KEY (ISBN) REFERENCES DAUSACH(ISBN)
);

CREATE TABLE DANGKY
(
	ISBN NUMBER,
	MA_DOCGIA NUMBER,
	NGAYGIO_DK DATE,
	GHICHU NVARCHAR2(255),
	CONSTRAINT PK_DK PRIMARY KEY(ISBN,MA_DOCGIA),
	CONSTRAINT FK_DANGKY_DAUSACH FOREIGN KEY (ISBN) REFERENCES DAUSACH(ISBN),
	CONSTRAINT FK_DANGKY_DOCGIA FOREIGN KEY (MA_DOCGIA) REFERENCES DOCGIA(MA_DOCGIA)
);

CREATE TABLE MUON
(
	ISBN NUMBER,
	MA_CUONSACH NUMBER,
	MA_DOCGIA NUMBER,
	NGAYGIO_MUON DATE,
	NGAY_HETHAN DATE,
	CONSTRAINT PK_MUON PRIMARY KEY(ISBN, MA_CUONSACH, MA_DOCGIA),
	CONSTRAINT FK_MUON_DOCGIA FOREIGN KEY (MA_DOCGIA) REFERENCES DOCGIA(MA_DOCGIA),
	CONSTRAINT FK_MUON_CUONSACH FOREIGN KEY (ISBN,MA_CUONSACH) REFERENCES CUONSACH(ISBN,MA_CUONSACH)
);

CREATE TABLE QUATRINHMUON
(
	ISBN NUMBER,
	MA_CUONSACH NUMBER,
	NGAYGIO_MUON DATE,
	MA_DOCGIA NUMBER,
	NGAY_HETHAN DATE,
	NGAY_TRA DATE,
	TIEN_MUON NUMBER,
	TIEN_DATRA NUMBER,
	TIEN_DATCOC NUMBER,
	GHICHU NVARCHAR2(255),
	CONSTRAINT PK_QTMUON PRIMARY KEY(ISBN,MA_CUONSACH,NGAYGIO_MUON),
	CONSTRAINT FK_QUATRINHMUON_CUONSACH FOREIGN KEY (ISBN,MA_CUONSACH) REFERENCES CUONSACH(ISBN,MA_CUONSACH),
	CONSTRAINT FK_QUATRINHMUON_DOCGIA FOREIGN KEY (MA_DOCGIA) REFERENCES DOCGIA(MA_DOCGIA)
);