--ĐỀ ÔN SỐ 4

---------------------------------------------------------------
--Câu 1. DDL
CREATE DATABASE DE4_KHACHHANG
USE DE4_KHACHHANG

CREATE TABLE KHACHHANG
(
	MAKH CHAR(5),
	HOTEN VARCHAR(30),
	DIACHI VARCHAR(30),
	SODT VARCHAR(15),
	LOAIKH VARCHAR(10),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MaKH)
)

CREATE TABLE BANG_DIA 
(
	MABD CHAR(5),
	TENBD VARCHAR(25),
	THELOAI VARCHAR(25),
	CONSTRAINT PK_BANG_DIA  PRIMARY KEY (MABD)
)

CREATE TABLE PHIEUTHUE 
(
	 MAPT CHAR(5),
	 MAKH CHAR(5),
	 NGAYTHUE SMALLDATETIME,
	 NGAYTTRA SMALLDATETIME,
	 SOLUONGTHUE INT,
	 CONSTRAINT PK_PHIEUTHUE   PRIMARY KEY (MAPT)
)

CREATE TABLE CHITIET_PM 
(
	MAPT CHAR(5) NOT NULL,
	MABD CHAR(5) NOT NULL,
	CONSTRAINT PK_CHITIET_PM PRIMARY KEY(MAPT,MABD)
)

--Thêm khóa ngoại 
ALTER TABLE PHIEUTHUE 
ADD CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)

ALTER TABLE CHITIET_PM 
ADD CONSTRAINT FK_MAPT FOREIGN KEY(MAPT) REFERENCES PHIEUTHUE(MAPT)

ALTER TABLE CHITIET_PM 
ADD CONSTRAINT FK_MABD FOREIGN KEY(MABD) REFERENCES BANG_DIA(MABD)

---------------------------------------------------------------
--Câu 2: TRIGGER
--2.1. Thể loại băng đĩa chỉ thuộc các thể loại sau “ca nhạc”, “phim hành động”, “phim tình 
--cảm”, “phim hoạt hình”. (1.5 đ) 
ALTER TABLE BANG_DIA 
ADD CONSTRAINT CK_THELOAI CHECK(THELOAI IN('ca nhạc','phim hành động','phim tình cảm','phim hoạt hình'))

--2.2. Chỉ những khách hàng thuộc loại VIP mới được thuê với số lượng băng đĩa trên 5. 
--(1.5 đ) 
GO
CREATE TRIGGER TRG_SLUONGTHUE ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAKH CHAR(5), @LOAIKH VARCHAR(10), @SOLUONGTHUE INT
	SELECT @MAKH = MAKH, @SOLUONGTHUE = SOLUONGTHUE FROM INSERTED
	SELECT @LOAIKH = LOAIKH FROM KHACHHANG WHERE MAKH = @MAKH
	IF @LOAIKH = 'VIP' AND @SOLUONGTHUE < 5
	BEGIN
		RAISERROR('Khách hàng VIP phải thuê trên 5 băng đĩa',16,1)
		ROLLBACK TRAN
	END
END

---------------------------------------------------------------
--Câu 3: TRUY VẤN
--3.1. Tìm các khách hàng (MaDG,HoTen) đã thuê băng đĩa  thuộc thể loại phim “Tình 
--cảm” có số lượng thuê lớn hơn 3. (1.5 đ)  
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH 
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT 
AND CHITIET_PM.MABD = BANG_DIA.MABD 
AND BANG_DIA.THELOAI = 'Tình cảm'
AND PHIEUTHUE.SOLUONGTHUE > 3


--3.2. Tìm các khách hàng(MaDG,HoTen) thuộc loại VIP đã thuê nhiều băng đĩa nhất. (1.5 đ) 
SELECT TOP 1 WITH TIES KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
AND KHACHHANG.LOAIKH = 'VIP'
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SUM(PHIEUTHUE.SOLUONGTHUE) DESC


--3.3. Trong mỗi thể loại băng đĩa, cho biết tên khách hàng nào đã thuê nhiều băng đĩa nhất. 
--(1 đ)  
SELECT BANG_DIA.THELOAI, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT
AND CHITIET_PM.MABD = BANG_DIA.MABD
GROUP BY BANG_DIA.THELOAI, KHACHHANG.HOTEN
HAVING SUM(PHIEUTHUE.SOLUONGTHUE) >= ALL (
	SELECT SUM(PHIEUTHUE.SOLUONGTHUE)
	FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
	WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
	AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT
	AND CHITIET_PM.MABD = BANG_DIA.MABD
	GROUP BY BANG_DIA.THELOAI, KHACHHANG.HOTEN
)