--ĐỀ ÔN SỐ 3

---------------------------------------------------------------
--Câu 1. DDL
CREATE DATABASE DE3_DOCGIA
USE DE3_DOCGIA

CREATE TABLE DOCGIA 
(
	MADG CHAR(5),
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(30),
	SODT VARCHAR(15),
	CONSTRAINT PK_DOCGIA PRIMARY KEY (MADG)
)

CREATE TABLE SACH
(
	MASACH CHAR(5),
	TENSACH VARCHAR(25),
	THELOAI VARCHAR(25),
	NHAXUATBAN VARCHAR(30),
	CONSTRAINT PK_SACH PRIMARY KEY (MASACH)
)

CREATE TABLE PHIEUTHUE
(
	MAPT CHAR(5),
	MADG CHAR(5) NOT NULL,
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOSACHTHUE INT
	CONSTRAINT PK_PHIEUTHUE PRIMARY KEY (MAPT)
)

CREATE TABLE CHITIET_PM 
(
	MAPT CHAR(5),
	MASACH CHAR(5),
	CONSTRAINT PK_CHITIET_PM PRIMARY KEY (MAPT,MASACH)
)

--Thêm khóa ngoại 
ALTER TABLE CHITIET_PM 
ADD CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT)

ALTER TABLE CHITIET_PM 
ADD CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)

ALTER TABLE PHIEUTHUE 
ADD CONSTRAINT FK_MADG FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)

---------------------------------------------------------------
--Câu 2: TRIGGER
--2.1. Mỗi lần thuê  sách, độc giả không được thuê quá 10 ngày. (1.5 đ) 
ALTER TABLE PHIEUTHUE 
ADD CONSTRAINT CK_NGAYTHUE_NGAYTRA CHECK (DATEDIFF(DAY,NGAYTHUE,NGAYTRA) <= 10)

--2.2. Số sách thuê trong bảng phiếu thuê bằng tổng số lần thuê sách có trong bảng chi tiết 
--phiếu thuê. (1.5 đ) 
GO
CREATE TRIGGER TRG_SOSACHTHUE ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAPT CHAR(5), @SOSACHTHUE INT, @TONGSOLAN INT
	SELECT @MAPT = MAPT FROM INSERTED
	SELECT @SOSACHTHUE = SOSACHTHUE FROM INSERTED
	SELECT @TONGSOLAN = COUNT(*) FROM CHITIET_PM WHERE MAPT = @MAPT

	IF @SOSACHTHUE <> @TONGSOLAN
		BEGIN
			RAISERROR('Số sách thuê trong bảng phiếu thuê bằng tổng số lần thuê sách có trong bảng chi tiết phiếu thuê.',16,1)
			ROLLBACK TRAN
		END
	ELSE
		BEGIN
			UPDATE PHIEUTHUE SET SOSACHTHUE = @TONGSOLAN WHERE MAPT = @MAPT
		END
END

DROP TRIGGER TRG_SOSACHTHUE

---------------------------------------------------------------
--Câu 3: TRUY VẤN
--3.1. Tìm các độc giả (MaDG,HoTen) đã thuê sách thuộc thể loại “Tin học” trong năm 
--2007. (1.5 đ)  
SELECT DISTINCT DOCGIA.MADG, DOCGIA.HOTEN
FROM DOCGIA, PHIEUTHUE, CHITIET_PM, SACH
WHERE DOCGIA.MADG = PHIEUTHUE.MADG 
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT 
AND CHITIET_PM.MASACH = SACH.MASACH 
AND SACH.THELOAI = 'Tin học' AND YEAR(PHIEUTHUE.NGAYTHUE) = 2007 


--3.2. Tìm các độc giả (MaDG,HoTen) đã thuê nhiều thể loại sách nhất. (1.5 đ)  
SELECT TOP 1 WITH TIES DOCGIA.MADG, DOCGIA.HOTEN
FROM DOCGIA, PHIEUTHUE, CHITIET_PM, SACH
WHERE DOCGIA.MADG = PHIEUTHUE.MADG AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT AND CHITIET_PM.MASACH = SACH.MASACH
GROUP BY DOCGIA.MADG, DOCGIA.HOTEN
ORDER BY COUNT(DISTINCT THELOAI) DESC

--3.3. Trong mỗi thể loại sách, cho biết tên sách được thuê nhiều nhất. (1 đ)  
SELECT DISTINCT THELOAI, TENSACH
FROM SACH, CHITIET_PM
WHERE SACH.MASACH = CHITIET_PM.MASACH
GROUP BY THELOAI, TENSACH
HAVING COUNT (CHITIET_PM.MASACH) >= ALL (
	SELECT COUNT(CHITIET_PM.MASACH)
	FROM SACH, CHITIET_PM
	WHERE SACH.MASACH = CHITIET_PM.MASACH
)
