CREATE DATABASE DETHITHUSO4

USE DETHITHUSO4

CREATE TABLE KHACHHANG (
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	DIACHI VARCHAR(30),
	SODT VARCHAR(15),
	LOAIKH VARCHAR(10)
	)
GO
CREATE TABLE BANG_DIA (
	MABD CHAR(5) PRIMARY KEY,
	TENBD VARCHAR(25),
	THELOAI VARCHAR(25),
	)
GO
CREATE TABLE PHIEUTHUE (
	 MAPT CHAR(5) PRIMARY KEY,
	 MAKH CHAR(5),
	 NGAYTHUE SMALLDATETIME,
	 NGAYTTRA SMALLDATETIME,
	 SOLUONGTHUE INT
	 )
GO
CREATE TABLE CHITIET_PM (
	MAPT CHAR(5) NOT NULL,
	MABD CHAR(5) NOT NULL,
	CONSTRAINT PK_CHITIET_PM PRIMARY KEY(MAPT,MABD)
)

ALTER TABLE PHIEUTHUE ADD CONSTRAINT FK_MAKH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
GO
ALTER TABLE CHITIET_PM ADD CONSTRAINT FK_MAPT FOREIGN KEY(MAPT) REFERENCES PHIEUTHUE(MAPT)
GO
ALTER TABLE CHITIET_PM ADD CONSTRAINT FK_MABD FOREIGN KEY(MABD) REFERENCES BANG_DIA(MABD)

--Thể loại băng đĩa chỉ thuộc các thể loại sau “ca nhạc”, “phim hành động”, “phim tình cảm”, “phim hoạt hình”. 
ALTER TABLE BANG_DIA ADD CONSTRAINT CK_THELOAI CHECK(THELOAI IN('ca nhạc','phim hành động','phim tình cảm','phim hoạt hình'))
GO
--Chỉ những khách hàng thuộc loại VIP mới được thuê với số lượng băng đĩa trên 5.
CREATE TRIGGER TRG_SLUONGTHUE ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAKH CHAR(5), @LOAIKH VARCHAR(10), @SOLUONGTHUE INT
	SELECT @MAKH = MAKH, @SOLUONGTHUE = SOLUONGTHUE FROM INSERTED
	SELECT @LOAIKH = LOAIKH FROM KHACHHANG WHERE MAKH = @MAKH
	IF @LOAIKH = 'VIP' AND @SOLUONGTHUE < 5
	BEGIN
		RAISERROR('Khách hàng VIP phải thuê trên 5 băng đĩa',16,1)
		ROLLBACK TRAN
	END
END

--Tìm các khách hàng (MaDG,HoTen) đã thuê băng đĩa thuộc thể loại phim “Tình cảm” có số lượng thuê lớn hơn 3. 
SELECT KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH 
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT 
AND CHITIET_PM.MABD = BANG_DIA.MABD 
AND BANG_DIA.THELOAI = 'Tình cảm'
AND PHIEUTHUE.SOLUONGTHUE > 3

--Tìm các khách hàng(MaKH,HoTen) thuộc loại VIP đã thuê nhiều băng đĩa nhất.
SELECT TOP 1 WITH TIES KHACHHANG.MAKH, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
AND KHACHHANG.LOAIKH = 'VIP'
GROUP BY KHACHHANG.MAKH, KHACHHANG.HOTEN
ORDER BY SUM(PHIEUTHUE.SOLUONGTHUE) DESC

--Trong mỗi thể loại băng đĩa, cho biết tên khách hàng nào đã thuê nhiều băng đĩa nhất.
SELECT BANG_DIA.THELOAI, KHACHHANG.HOTEN
FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT
AND CHITIET_PM.MABD = BANG_DIA.MABD
GROUP BY BANG_DIA.THELOAI, KHACHHANG.HOTEN
HAVING SUM(PHIEUTHUE.SOLUONGTHUE) >= ALL (
	SELECT SUM(PHIEUTHUE.SOLUONGTHUE)
	FROM KHACHHANG, PHIEUTHUE, CHITIET_PM, BANG_DIA
	WHERE KHACHHANG.MAKH = PHIEUTHUE.MAKH
	AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT
	AND CHITIET_PM.MABD = BANG_DIA.MABD
	GROUP BY BANG_DIA.THELOAI, KHACHHANG.HOTEN
)