CREATE DATABASE DETHITHUSO2
GO
USE DETHITHUSO2

CREATE TABLE NHANVIEN (
	MANV CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(20),
	NGAYVL SMALLDATETIME,
	HSLUONG NUMERIC(4,2),
	MAPHONG CHAR(5),
	)
GO
CREATE TABLE PHONGBAN (
	MAPHONG CHAR(5) PRIMARY KEY,
	TENPHONG VARCHAR(25),
	TRUONGPHONG CHAR(5),
	)
GO
CREATE TABLE XE (
	MAXE CHAR(5) PRIMARY KEY,
	LOAIXE VARCHAR(20),
	SOCHONGOI INT,
	NAMSX INT,
	)
GO
CREATE TABLE PHANCONG (
	MAPC CHAR(5) PRIMARY KEY,
	MANV CHAR(5) NOT NULL,
	MAXE CHAR(5) NOT NULL,
	NGAYDI SMALLDATETIME,
	NGAYVE SMALLDATETIME,
	NOIDEN VARCHAR(25)
	)

ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO
ALTER TABLE PHANCONG
ADD CONSTRAINT FK_PHANCONG_XE FOREIGN KEY (MAXE) REFERENCES XE(MAXE)
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NHANVIEN_PHONGBAN FOREIGN KEY (MAPHONG) REFERENCES PHONGBAN(MAPHONG)
GO
--Năm sản xuất của xe loại Toyota phải từ năm 2006 trở về sau. 
ALTER TABLE XE ADD CONSTRAINT CK_XE_NAMSX CHECK (LOAIXE = 'Toyota' AND NAMSX >= 2006)
GO
--Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota.
CREATE TRIGGER TR_PHANCONG_LOAIXE
ON PHANCONG
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAXE CHAR(5), @MAPHONG CHAR(5), @LOAIXE VARCHAR(20), @MANV CHAR(5), @MAPC CHAR(5), @TENPHONG VARCHAR(25)
	SELECT @MAXE = MAXE, @MANV =MANV FROM INSERTED
	SELECT @MAPC = MAPC FROM PHANCONG WHERE MANV = @MANV
	SELECT @LOAIXE = LOAIXE FROM XE WHERE MAXE = @MAXE
	SELECT @MAPHONG = MAPHONG FROM NHANVIEN WHERE MANV = @MANV
	SELECT @TENPHONG = TENPHONG FROM PHONGBAN WHERE MAPHONG = @MAPHONG

	IF @MAPHONG = 'Ngoại thành'
	BEGIN
		IF @LOAIXE <> 'Toyota'
		BEGIN
			RAISERROR('Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota.', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END
GO 
CREATE TRIGGER TR_NHANVIEN_UPDATE
ON NHANVIEN
FOR UPDATE
AS
BEGIN
	DECLARE @MAXE CHAR(5), @MAPHONG CHAR(5), @LOAIXE VARCHAR(20), @MANV CHAR(5), @MAPC CHAR(5)
	
	SELECT @MANV = MANV, @MAPHONG = MAPHONG FROM INSERTED
	SELECT @MAPC = MAPC FROM PHANCONG WHERE MANV = @MANV
	SELECT @LOAIXE = LOAIXE FROM XE WHERE MAXE = @MAXE
	
	IF @MAPHONG = 'Ngoại thành'
	BEGIN
		IF @LOAIXE <> 'Toyota'
		BEGIN
			RAISERROR('Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota.', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END
GO
CREATE TRIGGER TR_XE_UPDATE
ON XE
FOR UPDATE
AS
BEGIN
	DECLARE @MAXE CHAR(5), @MAPHONG CHAR(5), @LOAIXE VARCHAR(20), @MANV CHAR(5), @MAPC CHAR(5)

	SELECT @MAXE = MAXE, @LOAIXE = LOAIXE FROM INSERTED
	SELECT @MANV = MANV FROM PHANCONG WHERE MAXE = @MAXE
	SELECT @MAPHONG = MAPHONG FROM NHANVIEN WHERE MANV = @MANV

	IF @MAPHONG = 'Ngoại thành'
	BEGIN
		IF @LOAIXE <> 'Toyota'
		BEGIN
			RAISERROR('Nhân viên thuộc phòng lái xe “Ngoại thành” chỉ được phân công lái xe loại Toyota.', 16, 1)
			ROLLBACK TRANSACTION
		END
	END
END

DROP TRIGGER TR_PHANCONG_LOAIXE
DROP TRIGGER TR_NHANVIEN_UPDATE
DROP TRIGGER TR_XE_UPDATE

--Tìm nhân viên (MaNV,HoTen) thuộc phòng lái xe “Nội thành” được phân công lái loại xe Toyota có số chỗ ngồi là 4.
SELECT NHANVIEN.MANV, NHANVIEN.HOTEN
FROM NHANVIEN, PHONGBAN, XE, PHANCONG
WHERE NHANVIEN.MANV=PHANCONG.MANV AND PHANCONG.MAXE=XE.MAXE AND PHONGBAN.MAPHONG=NHANVIEN.MAPHONG
	AND TENPHONG='Noi Thanh' AND LOAIXE='Toyota' AND SOCHONGOI=4

--Tìm nhân viên(MANV,HoTen) là trưởng phòng được phân công lái tất cả các loại xe.
SELECT NHANVIEN.MANV, NHANVIEN.HOTEN
FROM NHANVIEN, PHONGBAN
WHERE NHANVIEN.MANV = PHONGBAN.TRUONGPHONG 
	AND NHANVIEN.MAPHONG=PHONGBAN.MAPHONG
	AND NOT EXISTS (
		SELECT * 
		FROM XE
		WHERE NOT EXISTS (
			SELECT *
			FROM PHANCONG
			WHERE PHANCONG.MAXE=XE.MAXE
			AND PHANCONG.MANV=NHANVIEN.MANV
		)
	)

--Trong mỗi phòng ban,tìm nhân viên (MaNV,HoTen) được phân công lái ít nhất loại xe Toyota. 
SELECT PHONGBAN.TENPHONG, NHANVIEN.MANV, NHANVIEN.HOTEN
FROM NHANVIEN, PHONGBAN, PHANCONG, XE
WHERE NHANVIEN.MANV=PHANCONG.MANV AND PHANCONG.MAXE=XE.MAXE AND PHONGBAN.MAPHONG=NHANVIEN.MAPHONG
GROUP BY PHONGBAN.TENPHONG, NHANVIEN.MANV, NHANVIEN.HOTEN
HAVING COUNT(LOAIXE) = (
	SELECT TOP 1 COUNT(LOAIXE)
	FROM NHANVIEN, PHONGBAN, PHANCONG, XE
	WHERE NHANVIEN.MANV=PHANCONG.MANV AND PHANCONG.MAXE=XE.MAXE AND PHONGBAN.MAPHONG=NHANVIEN.MAPHONG
	AND LOAIXE='Toyota'
	ORDER BY COUNT(LOAIXE) ASC
)



