CREATE DATABASE DETHITHUSO3
USE DETHITHUSO3

CREATE TABLE DOCGIA (
	MADG CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	DIACHI VARCHAR(30),
	SODT VARCHAR(15)
	)
GO
CREATE TABLE SACH (
	MASACH CHAR(5) PRIMARY KEY,
	TENSACH VARCHAR(25),
	THELOAI VARCHAR(25),
	NHAXUATBAN VARCHAR(30)
	)
GO
CREATE TABLE PHIEUTHUE (
	MAPT CHAR(5) PRIMARY KEY,
	MADG CHAR(5) NOT NULL,
	NGAYTHUE SMALLDATETIME,
	NGAYTRA SMALLDATETIME,
	SOSACHTHUE INT
	)
GO
CREATE TABLE CHITIET_PM (
	MAPT CHAR(5) NOT NULL,
	MASACH CHAR(5) NOT NULL,
	CONSTRAINT PK_CHITIET_PM PRIMARY KEY (MAPT,MASACH)
	)

ALTER TABLE CHITIET_PM ADD CONSTRAINT FK_MAPT FOREIGN KEY (MAPT) REFERENCES PHIEUTHUE(MAPT)
GO
ALTER TABLE CHITIET_PM ADD CONSTRAINT FK_MASACH FOREIGN KEY (MASACH) REFERENCES SACH(MASACH)
GO
ALTER TABLE PHIEUTHUE ADD CONSTRAINT FK_MADG FOREIGN KEY (MADG) REFERENCES DOCGIA(MADG)

--Mỗi lần thuê sách, độc giả không được thuê quá 10 ngày. 
ALTER TABLE PHIEUTHUE ADD CONSTRAINT CK_NGAYTHUE_NGAYTRA CHECK (DATEDIFF(DAY,NGAYTHUE,NGAYTRA) <= 10)
GO
--Số sách thuê trong bảng phiếu thuê bằng tổng số lần thuê sách có trong bảng chi tiết phiếu thuê.
CREATE TRIGGER TRG_SOSACHTHUE ON PHIEUTHUE
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAPT CHAR(5), @SOSACHTHUE INT, @TONGSOLAN INT
	SELECT @MAPT = MAPT FROM INSERTED
	SELECT @SOSACHTHUE = SOSACHTHUE FROM INSERTED
	SELECT @TONGSOLAN = COUNT(*) FROM CHITIET_PM WHERE MAPT = @MAPT

	IF @SOSACHTHUE <> @TONGSOLAN
		BEGIN
			RAISERROR('Số sách thuê trong bảng phiếu thuê bằng tổng số lần thuê sách có trong bảng chi tiết phiếu thuê.',16,1)
			ROLLBACK TRAN
		END
	ELSE
		BEGIN
			UPDATE PHIEUTHUE SET SOSACHTHUE = @TONGSOLAN WHERE MAPT = @MAPT
		END
END

DROP TRIGGER TRG_SOSACHTHUE
--Tìm các độc giả (MaDG,HoTen) đã thuê sách thuộc thể loại “Tin học” trong năm 2007.
SELECT DISTINCT DOCGIA.MADG, DOCGIA.HOTEN
FROM DOCGIA, PHIEUTHUE, CHITIET_PM, SACH
WHERE DOCGIA.MADG = PHIEUTHUE.MADG 
AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT 
AND CHITIET_PM.MASACH = SACH.MASACH 
AND SACH.THELOAI = 'Tin học' AND YEAR(PHIEUTHUE.NGAYTHUE) = 2007 

--Tìm các độc giả (MaDG,HoTen) đã thuê nhiều thể loại sách nhất. 
SELECT TOP 1 WITH TIES DOCGIA.MADG, DOCGIA.HOTEN
FROM DOCGIA, PHIEUTHUE, CHITIET_PM, SACH
WHERE DOCGIA.MADG = PHIEUTHUE.MADG AND PHIEUTHUE.MAPT = CHITIET_PM.MAPT AND CHITIET_PM.MASACH = SACH.MASACH
GROUP BY DOCGIA.MADG, DOCGIA.HOTEN
ORDER BY COUNT(DISTINCT THELOAI) DESC

--Trong mỗi thể loại sách, cho biết tên sách được thuê nhiều nhất. 
SELECT DISTINCT THELOAI, TENSACH
FROM SACH, CHITIET_PM
WHERE SACH.MASACH = CHITIET_PM.MASACH
GROUP BY THELOAI, TENSACH
HAVING COUNT (CHITIET_PM.MASACH) >= ALL (
	SELECT COUNT(CHITIET_PM.MASACH)
	FROM SACH, CHITIET_PM
	WHERE SACH.MASACH = CHITIET_PM.MASACH
)
