--Câu 1
CREATE DATABASE QLCASI
USE QLCASI


CREATE TABLE CASI
(
	MACS CHAR(5),
	HOTEN VARCHAR(30),
	NGAYSINH SMALLDATETIME,
	SODT VARCHAR(15),
	CONSTRAINT PK_CASI PRIMARY KEY (MACS)
)

CREATE TABLE BAIHAT
(
	MABH CHAR(5),
	TENBH VARCHAR(25),
	NGAYST SMALLDATETIME,
	MATG CHAR(5),
	CONSTRAINT PK_BAIHAT PRIMARY KEY (MABH)
)

CREATE TABLE TACGIA
(
	MATG CHAR(5),
	HOTEN VARCHAR(20),
	NGSINH SMALLDATETIME,
	SODT INT,
	CONSTRAINT PK_TACGIA PRIMARY KEY (MATG)
)

CREATE TABLE LICHDIEN
(
	NGAYDIEN SMALLDATETIME,
	MACS CHAR(5),
	MABH CHAR(5),
	DIADIEM VARCHAR(50),
	TENSK VARCHAR(20),
	PRIMARY KEY (NGAYDIEN, MACS, MABH)
)

--Thêm khóa ngoại 
ALTER TABLE BAIHAT
ADD CONSTRAINT FK_BH FOREIGN KEY (MATG) REFERENCES TACGIA (MATG)

ALTER TABLE LICHDIEN
ADD CONSTRAINT FK1_LD FOREIGN KEY (MACS) REFERENCES CASI (MACS)

ALTER TABLE LICHDIEN
ADD CONSTRAINT FK2_LD FOREIGN KEY (MABH) REFERENCES BAIHAT (MABH)

---------------------------------------------------------------
--Câu 2: TRIGGER
--2.1. 
GO 
CREATE TRIGGER TRG_SOLUONGBH
ON LICHDIEN
FOR INSERT, UPDATE
AS 
BEGIN
	DECLARE @MACS CHAR(5), @NGAYDIEN SMALLDATETIME, @SLBH INT

	SELECT @MACS = MACS, @NGAYDIEN = NGAYDIEN
	FROM INSERTED

	SELECT @SLBH = COUNT(*)
	FROM LICHDIEN
	WHERE MACS = @MACS
	AND NGAYDIEN = @NGAYDIEN

	IF (@SLBH > 10)
	BEGIN 
		RAISERROR ('Mỗi ca sĩ không được hát quá 10 bài trong cùng một ngày diễn.', 16, 1)
        ROLLBACK TRANSACTION
	END
END


--2.2
GO
CREATE TRIGGER TRG_KTNGAYSANGTAC
ON BAIHAT
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @MATG CHAR(5), @NGSINH SMALLDATETIME, @NGAYST SMALLDATETIME
    
    SELECT @MATG = MATG, @NGSINH = NGSINH
    FROM INSERTED;
    
    SELECT @NGAYST= NGAYST
    FROM BAIHAT
    WHERE MATG = @MATG;
    
    IF (@NGAYST < @NGSINH)
    BEGIN
        RAISERROR ('Ngày sáng tác phải lớn hơn ngày sinh của tác giả.', 16, 1)
        ROLLBACK TRANSACTION
    END
END


GO
---------------------------------------------------------------
--Câu 3: TRUY VẤN
--3a
SELECT BH.MABH, BH.TENBH
FROM BAIHAT BH, LICHDIEN LD
WHERE BH.MABH = LD.MABH
AND LD.NGAYDIEN = '2023-11-19' 
AND LD.DIADIEM = 'Phòng trà Không Tên'

--3B
SELECT CS.MACS, CS.HOTEN
FROM CASI CS, LICHDIEN LD, BAIHAT BH, TACGIA TG
WHERE CS.MACS = LD.MACS AND LD.MABH = BH.MABH AND BH.MATG = TG.MATG
AND TG.HOTEN = 'Trịnh Công Sơn'
AND YEAR(BH.NGAYST) < 1998
ORDER BY CS.HOTEN DESC

--3C
SELECT TACGIA.MATG, TACGIA.HOTEN, COUNT(BAIHAT.MABH) AS SoLuongBaiHat
FROM TACGIA , BAIHAT
WHERE TACGIA.MATG = BAIHAT.MATG
GROUP BY TACGIA.MATG, TACGIA.HOTEN

--3D
SELECT CS.HOTEN
FROM CASI CS, LICHDIEN LD, BAIHAT BH, TACGIA TG
WHERE CS.MACS = LD.MACS AND LD.MABH = BH.MABH AND TG.MATG = BH.MATG
AND LD.NGAYDIEN = '2023-12-22'
AND LD.DIADIEM = 'Sân vận động Mỹ Đình Hà Nội'
AND TG.HOTEN = 'Hoàng Phú'
INTERSECT
SELECT CS.HOTEN
FROM CASI CS, LICHDIEN LD, BAIHAT BH, TACGIA TG
WHERE CS.MACS = LD.MACS AND LD.MABH = BH.MABH AND TG.MATG = BH.MATG
AND LD.NGAYDIEN = '2023-12-22'
AND LD.DIADIEM = 'Sân vận động Mỹ Đình Hà Nội'
AND TG.HOTEN = 'Hoàng Quý'

--3e
SELECT CS.HOTEN
FROM CASI CS, LICHDIEN LD, BAIHAT BH, TACGIA TG
WHERE CS.MACS = LD.MACS AND LD.MABH = BH.MABH AND BH.MATG = TG.MATG
AND TG.HOTEN = 'Trịnh Công Sơn'
AND YEAR(BH.NGAYST) >= 1990
AND YEAR(BH.NGAYST) <= 1995
GROUP BY CS.HOTEN
HAVING COUNT (DISTINCT BH.MABH) = 
							(
								SELECT COUNT(*) AS TONGBH
								FROM BAIHAT BH2, TACGIA TG2
								WHERE BH2.MATG = TG2.MATG
								AND TG2.HOTEN = 'Trịnh Công Sơn'
								AND YEAR(BH2.NGAYST) >= 1990
								AND YEAR(BH2.NGAYST) <= 1995
							)

--3f
SELECT TG.MATG, TG.HOTEN
FROM TACGIA TG, BAIHAT BH, LICHDIEN LD
WHERE TG.MATG = BH.MATG AND BH.MABH = LD.MABH
GROUP BY TG.MATG, TG.HOTEN
HAVING COUNT(*) =
				(
					SELECT TOP 1 WITH TIES COUNT(*) SONGCAIHAT
					FROM BAIHAT BH2, LICHDIEN LD2
					WHERE BH2.MABH = LD2.MABH
					GROUP BY BH2.MATG
					ORDER BY SONGCAIHAT DESC
				)









    


















