-- Tạo database
CREATE DATABASE QuanLyBanHang;
USE QuanLyBanHang;

-- Tạo bảng KHACHANG
CREATE TABLE KHACHANG (
    MAKH CHAR(10) PRIMARY KEY,
    TENKH VARCHAR(50),
    DIACHI VARCHAR(100)
);

-- Tạo bảng HANGHOA
CREATE TABLE HANGHOA (
    MAHH CHAR(10) PRIMARY KEY,
    TENHH VARCHAR(50),
    GIA DECIMAL(10, 2)
);

-- Tạo bảng DONHANG
CREATE TABLE DONHANG (
    MADH CHAR(10) PRIMARY KEY,
    TENNH VARCHAR(50),
    NGAYDAT DATE,
    MAKH CHAR(10),
    FOREIGN KEY (MAKH) REFERENCES KHACHANG(MAKH)
);

-- Tạo bảng CHITIETDONHANG
CREATE TABLE CHITIETDONHANG (
    MADH CHAR(10),
    MAHH CHAR(10),
    SOLUONG INT,
    PRIMARY KEY (MADH, MAHH),
    FOREIGN KEY (MADH) REFERENCES DONHANG(MADH),
    FOREIGN KEY (MAHH) REFERENCES HANGHOA(MAHH)
);
-- Thêm dữ liệu mẫu vào bảng KHACHANG
INSERT INTO KHACHANG (MAKH, TENKH, DIACHI) VALUES
('KH001', 'Nguyen Van A', 'Hanoi'),
('KH002', 'Tran Thi B', 'Hai Phong'),
('KH003', 'Le Van C', 'Da Nang');

-- Thêm dữ liệu mẫu vào bảng HANGHOA
INSERT INTO HANGHOA (MAHH, TENHH, GIA) VALUES
('HH001', 'Laptop Dell', 15000000),
('HH002', 'iPhone 14', 20000000),
('HH003', 'Samsung Galaxy', 18000000);

-- Thêm dữ liệu mẫu vào bảng DONHANG
INSERT INTO DONHANG (MADH, TENNH, NGAYDAT, MAKH) VALUES
('DH001', 'Don Hang 1', '2025-01-10', 'KH001'),
('DH002', 'Don Hang 2', '2025-01-11', 'KH002');

-- Thêm dữ liệu mẫu vào bảng CHITIETDONHANG
INSERT INTO CHITIETDONHANG (MADH, MAHH, SOLUONG) VALUES
('DH001', 'HH001', 2),
('DH001', 'HH002', 1),
('DH002', 'HH003', 3);
