/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIandBUS;

import GUIandBUS.QLKH;
import GUIandBUS.QLNV;

/**
 *
 * @author fanta
 */
public class AdminPage_new extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage_new
     */
    public AdminPage_new() {
        initComponents();
        // Thiết lập penel
        initComponents();
        //Các bước set giao diện
        /*1. Set kích thước giao diện*/
        setSize(700,450);
        /*2. Set nút chọn tắt mặc định EXIT_ON_CLOSE*/ 
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        /*3. Tiêu đề*/
        setTitle("Adminpage");
        /*4. Không cho phóng to*/
        setResizable(false);
        /*5. Vị trí trang*/
        setLocation(100,40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btBack = new javax.swing.JButton();
        btQLKH = new javax.swing.JButton();
        btQLNV = new javax.swing.JButton();
        btQLPHIM = new javax.swing.JButton();
        btQLSC1 = new javax.swing.JButton();
        btQLSC = new javax.swing.JButton();
        btQLLC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btBack.setBackground(new java.awt.Color(255, 255, 204));
        btBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 0, 0));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/exit.png"))); // NOI18N
        btBack.setText("QUAY LẠI");
        btBack.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });
        getContentPane().add(btBack);
        btBack.setBounds(510, 310, 140, 50);

        btQLKH.setBackground(new java.awt.Color(204, 255, 204));
        btQLKH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLKH.setForeground(new java.awt.Color(51, 51, 255));
        btQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/customer-review.png"))); // NOI18N
        btQLKH.setText("QUẢN LÝ KHÁCH HÀNG");
        btQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLKH.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLKHActionPerformed(evt);
            }
        });
        getContentPane().add(btQLKH);
        btQLKH.setBounds(20, 20, 200, 110);

        btQLNV.setBackground(new java.awt.Color(204, 255, 204));
        btQLNV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLNV.setForeground(new java.awt.Color(51, 51, 255));
        btQLNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/cinema (1).png"))); // NOI18N
        btQLNV.setText("QUẢN LÝ NHÂN VIÊN");
        btQLNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLNVActionPerformed(evt);
            }
        });
        getContentPane().add(btQLNV);
        btQLNV.setBounds(240, 20, 200, 110);

        btQLPHIM.setBackground(new java.awt.Color(204, 255, 204));
        btQLPHIM.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLPHIM.setForeground(new java.awt.Color(51, 51, 255));
        btQLPHIM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/movie.png"))); // NOI18N
        btQLPHIM.setText("QUẢN LÝ PHIM");
        btQLPHIM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLPHIM.setVerifyInputWhenFocusTarget(false);
        btQLPHIM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLPHIM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLPHIMActionPerformed(evt);
            }
        });
        getContentPane().add(btQLPHIM);
        btQLPHIM.setBounds(460, 20, 200, 110);

        btQLSC1.setBackground(new java.awt.Color(204, 255, 204));
        btQLSC1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLSC1.setForeground(new java.awt.Color(51, 51, 255));
        btQLSC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/board (1).png"))); // NOI18N
        btQLSC1.setText("QUẢN LÝ PHÒNG");
        btQLSC1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLSC1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLSC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLSC1ActionPerformed(evt);
            }
        });
        getContentPane().add(btQLSC1);
        btQLSC1.setBounds(460, 160, 200, 110);

        btQLSC.setBackground(new java.awt.Color(204, 255, 204));
        btQLSC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLSC.setForeground(new java.awt.Color(51, 51, 255));
        btQLSC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/discussion.png"))); // NOI18N
        btQLSC.setText("QUẢN LÝ SUẤT CHIẾU");
        btQLSC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLSC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLSC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLSCActionPerformed(evt);
            }
        });
        getContentPane().add(btQLSC);
        btQLSC.setBounds(240, 160, 200, 110);

        btQLLC.setBackground(new java.awt.Color(204, 255, 204));
        btQLLC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btQLLC.setForeground(new java.awt.Color(51, 51, 255));
        btQLLC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/calendar (1).png"))); // NOI18N
        btQLLC.setText("QUẢN LÝ LỊCH CHIẾU");
        btQLLC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btQLLC.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btQLLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQLLCActionPerformed(evt);
            }
        });
        getContentPane().add(btQLLC);
        btQLLC.setBounds(20, 160, 200, 110);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/abc.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 700, 380);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoiNguon/video-camera.png"))); // NOI18N
        jMenu1.setText(" Phần mềm quản lý rạp chiếu phim. Nhóm JTTeam. ADMINPAGE");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLKHActionPerformed
        // TODO add your handling code here:
        hide();
        QLKH.main(null);
    }//GEN-LAST:event_btQLKHActionPerformed

    private void btQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLNVActionPerformed
        // TODO add your handling code here:
        hide();
        QLNV.main(null);
    }//GEN-LAST:event_btQLNVActionPerformed

    private void btQLPHIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLPHIMActionPerformed
        // TODO add your handling code here:
        hide();
        QLPHIM.main(null);
    }//GEN-LAST:event_btQLPHIMActionPerformed

    private void btQLSCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLSCActionPerformed
        // TODO add your handling code here:
        hide();
        QLSC.main(null);
    }//GEN-LAST:event_btQLSCActionPerformed

    private void btQLLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLLCActionPerformed
        // TODO add your handling code here:
        hide();
        QLLC.main(null);
    }//GEN-LAST:event_btQLLCActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        hide();
        DangNhap.main(null);
    }//GEN-LAST:event_btBackActionPerformed

    private void btQLSC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQLSC1ActionPerformed
        // TODO add your handling code here:
        QLPHONG.main(null);
    }//GEN-LAST:event_btQLSC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage_new.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage_new().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btQLKH;
    private javax.swing.JButton btQLLC;
    private javax.swing.JButton btQLNV;
    private javax.swing.JButton btQLPHIM;
    private javax.swing.JButton btQLSC;
    private javax.swing.JButton btQLSC1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
