/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIandBUS;

/*import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.PreparedStatement;*/
import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;
import dao.ConnectionUtils;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import java.text.ParseException;
import net.sf.jasperreports.engine.JRException;
//----------------
public class DangNhap extends javax.swing.JFrame {
    /**
     * Creates new form DangNhap
     */
    @SuppressWarnings("OverridableMethodCallInConstructor")
    public DangNhap() {
        initComponents();
        // thiết lập kích thước cửa sổ
        this.setSize(720, 370);
        // trithiết lập thao tác đóng cửa sổ
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
       // cho phép cửa sổ hiển thị
        this.setVisible(true);
        // Không cho phóng to
         setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        user = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        dangki = new javax.swing.JButton();
        dangnhap = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 40, 322, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("TÀI KHOẢN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 120, 110, 40);

        user.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(440, 120, 241, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("MẬT KHẨU");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(320, 180, 110, 40);

        password.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(password);
        password.setBounds(440, 180, 241, 40);

        dangki.setBackground(new java.awt.Color(255, 255, 255));
        dangki.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dangki.setForeground(new java.awt.Color(51, 51, 51));
        dangki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/login (4).png"))); // NOI18N
        dangki.setText(" ĐĂNG KÍ");
        dangki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangkiActionPerformed(evt);
            }
        });
        getContentPane().add(dangki);
        dangki.setBounds(530, 260, 130, 40);

        dangnhap.setBackground(new java.awt.Color(255, 255, 255));
        dangnhap.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dangnhap.setForeground(new java.awt.Color(51, 51, 51));
        dangnhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoiNguon/login (3).png"))); // NOI18N
        dangnhap.setSelected(true);
        dangnhap.setText("  LOGIN");
        dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangnhapActionPerformed(evt);
            }
        });
        getContentPane().add(dangnhap);
        dangnhap.setBounds(370, 260, 120, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoiNguon/new.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, -150, 1460, 650);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangnhapActionPerformed
        // TODO add your handling code here:
          
        /* Neu nguoi dung nhap rong se thong bao rong*/
        if(user.getText().equals("")||password.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Tài Khoản không được để trống","Trống",JOptionPane.WARNING_MESSAGE);
        /*Tài khoản admin*/
        if(password.getText().equals("admin")&&user.getText().equals("admin")){
            JOptionPane.showMessageDialog(null,"Đăng nhập với tài khoản Admin!");
            hide();
            AdminPage_new ad =new AdminPage_new();
            AdminPage_new.main(null);}
        else{
            try{
                Connection con = null;
                try {
                    con = ConnectionUtils.getMyConnection();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
                }
              
                String SQL ="SELECT username,password FROM KHACHHANG\n"
                        + "WHERE username=? and password=?";
                PreparedStatement ps=con.prepareStatement(SQL);
                ps.setString(1, user.getText());
                ps.setString(2,password.getText());
                ResultSet rs = ps.executeQuery();
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(this,"Đăng nhập thành công!");
                    hide();
                   TrangThanhVien tv =new TrangThanhVien(user.getText());
                    TrangThanhVien.HienThi(user.getText());
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Tài khoản hoặc mật khẩu sai","Sai mật khẩu!",JOptionPane.ERROR_MESSAGE);
                }
            }catch (HeadlessException | SQLException ex)
            {
               System.out.println(ex);
            } catch (ClassNotFoundException | JRException ex) {
                Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
    }//GEN-LAST:event_dangnhapActionPerformed

    private void dangkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangkiActionPerformed
        // TODO add your handling code here:
        DangKi dk =new DangKi();
        DangKi.main(null);
    }//GEN-LAST:event_dangkiActionPerformed


 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DangNhap().setVisible(true);
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dangki;
    private javax.swing.JToggleButton dangnhap;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPasswordField password;
    private javax.swing.JFormattedTextField user;
    // End of variables declaration//GEN-END:variables

  
}
