/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIandBUS;

import dao.ConnectionUtils;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.RowFilter;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static oracle.sql.NUMBER.e;

/**
 *
 * @author fanta
 */
public class QLSC extends javax.swing.JFrame {

    /**
     * Creates new form QLSC
     */
    
    DefaultTableModel modelSuat = null;
    String ma;
    
    private void setTableSC(){    
        try (Connection con = ConnectionUtils.getMyConnection()){
            String SQL_SUAT = "SELECT MASUAT,THOIGIANBD,NGAYCHIEU FROM SUATCHIEU ORDER BY MASUAT";
            Statement statement = con.createStatement();
            ResultSet rs = statement.executeQuery(SQL_SUAT);
            SimpleDateFormat TimeFormatter = new SimpleDateFormat("HH:mm");
            SimpleDateFormat DateFormatter = new SimpleDateFormat("dd-MM-yyyy");
            modelSuat = (DefaultTableModel) tbSC.getModel();
            modelSuat.setRowCount(0);
            while(rs.next()){
                String MaSuat = rs.getString(1);
                String t_TGBD = TimeFormatter.format(rs.getTime(2));
                String d_NgChieu = DateFormatter.format(rs.getDate(3));
                modelSuat.addRow(new Object[]{MaSuat,t_TGBD,d_NgChieu});
                }
            con.close();
        } 
        catch (Exception ex){
            Logger.getLogger(QLSC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void getRowSC (int index){
        try{
            ma = ((String)(tbSC.getValueAt(index,0)));
            java.util.Date t_TGBD = new SimpleDateFormat("HH:mm").parse((String)(tbSC.getValueAt(index,1)));
            java.util.Date d_NgChieu = new SimpleDateFormat("dd-MM-yyyy").parse((String)(tbSC.getValueAt(index,2)));
            spin_TGBD.setValue((Object)t_TGBD);
            txtNgC.setDate(d_NgChieu);
        } catch(ParseException e){System.out.println(e);}
    }
    
    private void clearSC(){
        txtNgC.setDate(null);
        try {
            Date start_Time = new SimpleDateFormat("HH:mm").parse("00:00");
            Calendar cal = Calendar.getInstance();
            cal.setTime(start_Time);
            spin_TGBD.setValue(cal.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(QLSC.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public QLSC() {
        initComponents();
        setTableSC();
        clearSC();
        this.setSize(820, 320);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setTitle("Trang admin: quản lý suất chiếu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNgC = new com.toedter.calendar.JDateChooser();
        Date TGBD = new Date();
        SpinnerDateModel sm_BD =
        new SpinnerDateModel(TGBD, null, null, Calendar.HOUR_OF_DAY);
        spin_TGBD = new javax.swing.JSpinner(sm_BD);
        jLabel12 = new javax.swing.JLabel();
        btThem = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btLamMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbSC = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btBack = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Bắt đầu:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Ngày chiếu:");

        txtNgC.setDateFormatString("dd-MM-yyyy");
        txtNgC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        JSpinner.DateEditor de_BD = new JSpinner.DateEditor(spin_TGBD, "HH:mm");
        spin_TGBD.setEditor(de_BD);
        spin_TGBD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/diagram.png"))); // NOI18N
        jLabel12.setText("THÔNG TIN SUẤT CHIẾU");

        btThem.setBackground(new java.awt.Color(255, 255, 255));
        btThem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btThem.setForeground(new java.awt.Color(0, 153, 0));
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/checked (1).png"))); // NOI18N
        btThem.setText("Add");
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });

        btXoa.setBackground(new java.awt.Color(255, 255, 255));
        btXoa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btXoa.setForeground(new java.awt.Color(255, 0, 0));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/multiply.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });

        btSua.setBackground(new java.awt.Color(255, 255, 255));
        btSua.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btSua.setForeground(new java.awt.Color(255, 102, 0));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/wrench.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });

        btLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btLamMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/refresh.png"))); // NOI18N
        btLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spin_TGBD))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNgC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btThem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btXoa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spin_TGBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btThem)
                    .addComponent(btXoa)
                    .addComponent(btSua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btLamMoi)
                .addContainerGap())
        );

        try {
            Date start_Time = new SimpleDateFormat("HH:mm").parse("00:00");
            Calendar cal = Calendar.getInstance();
            cal.setTime(start_Time);
            spin_TGBD.setValue(cal.getTime());
        } catch (ParseException ex) {
            Logger.getLogger(QLSC.class.getName()).log(Level.SEVERE, null, ex);
        }

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbSC.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbSC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã", "Thời gian bắt đầu", "Ngày chiếu"
            }
        ));
        tbSC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbSC);
        if (tbSC.getColumnModel().getColumnCount() > 0) {
            tbSC.getColumnModel().getColumn(0).setMinWidth(40);
            tbSC.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbSC.getColumnModel().getColumn(0).setMaxWidth(40);
        }

        txtSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 51, 51), new java.awt.Color(0, 0, 255), new java.awt.Color(255, 51, 255), new java.awt.Color(0, 255, 0)));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Tìm kiếm:");

        btBack.setBackground(new java.awt.Color(255, 255, 255));
        btBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btBack.setForeground(new java.awt.Color(255, 0, 0));
        btBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIandBUS/exit.png"))); // NOI18N
        btBack.setText("Quay lại");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBack)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btBack)
                .addGap(127, 127, 127))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GoiNguon/video-camera.png"))); // NOI18N
        jMenu1.setText(" Phần mềm quản lý rạp chiếu phim. Nhóm JTTeam. ADMINPAGE: QUẢN LÝ SUẤT CHIẾU");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        try(Connection con = ConnectionUtils.getMyConnection()){
            SimpleDateFormat DateFormatter = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat TimeFormatter = new SimpleDateFormat("HH:mm");
            java.util.Date d_NgSC = txtNgC.getDate();
            java.util.Date t_TGBD = (Date)spin_TGBD.getValue();          
            String S_NgSC = DateFormatter.format(d_NgSC);
            String S_TGBD = TimeFormatter.format(t_TGBD);
            String SQL_SC="INSERT INTO SUATCHIEU(MASUAT,THOIGIANBD,NGAYCHIEU)"
            +"VALUES(MaSuat_seq5.nextval,to_date('"+S_TGBD+"','HH24:MI'),to_date('"+S_NgSC+"','dd-mm-yyyy'))";
            Statement stat_Suat = con.createStatement();
            stat_Suat.executeUpdate(SQL_SC);
            setTableSC();
            con.close();
            JOptionPane.showMessageDialog(this,"Thành công!");
            getRowSC(tbSC.getRowCount()-1);
        }catch (SQLException ex)
        {
             if(ex.getErrorCode()==20004)
             {
                 JOptionPane.showMessageDialog(this,"Giờ chiếu đã có trong một ngày chiếu\n"
                         + "Vui lòng thử lại!","Lỗi trùng giờ chiếu",JOptionPane.ERROR_MESSAGE);
             } else {
             }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLSC.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btThemActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        try(Connection con = ConnectionUtils.getMyConnection()){
            SimpleDateFormat DateFormatter = new SimpleDateFormat("dd-MM-yyyy");
            SimpleDateFormat TimeFormatter = new SimpleDateFormat("HH:mm");
            java.util.Date d_NgSC = txtNgC.getDate();
            java.util.Date t_TGBD = (Date)spin_TGBD.getValue();          
            String S_NgSC = DateFormatter.format(d_NgSC);
            String S_TGBD = TimeFormatter.format(t_TGBD);
            String SQL_SC="UPDATE SUATCHIEU SET THOIGIANBD = to_date('"+S_TGBD+"','HH24:MI'), NGAYCHIEU = to_date('"+S_NgSC+"','dd-mm-yyyy') WHERE MASUAT = "+ ma;
            Statement stat_Suat = con.createStatement();
            stat_Suat.executeUpdate(SQL_SC);
            setTableSC();
            con.close();
            JOptionPane.showMessageDialog(this,"Thành công!");
        }catch (SQLException ex)
        {
            if(ex.getErrorCode()==20004)
             {
                 JOptionPane.showMessageDialog(this,"Giờ chiếu đã có trong một ngày chiếu\n"
                         + "Vui lòng thử lại!","Lỗi trùng giờ chiếu",JOptionPane.ERROR_MESSAGE);
             }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(QLSC.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_btSuaActionPerformed

    private void btLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLamMoiActionPerformed
        // TODO add your handling code here:
        clearSC();
    }//GEN-LAST:event_btLamMoiActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        try(Connection con = ConnectionUtils.getMyConnection()){
            String SQL_Suat = "DELETE FROM SUATCHIEU WHERE MASUAT = "+ ma;
            Statement stat_Suat = con.createStatement();
            stat_Suat.executeUpdate(SQL_Suat);
            setTableSC();
            clearSC();
            con.close();
            JOptionPane.showMessageDialog(this,"Thành công!");
        } catch (Exception ex){
            JOptionPane.showMessageDialog(this,"Xóa không thành công!","Lỗi",JOptionPane.ERROR_MESSAGE);
            System.out.println(ex);
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbSCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSCMouseClicked
        // TODO add your handling code here:
        getRowSC(tbSC.getSelectedRow());
    }//GEN-LAST:event_tbSCMouseClicked

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        // TODO add your handling code here:
        hide();
        AdminPage_new.main(null);
    }//GEN-LAST:event_btBackActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        DefaultTableModel SearchTable = (DefaultTableModel) tbSC.getModel();
        String search = txtSearch.getText();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(SearchTable);
        tbSC.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtSearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btLamMoi;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spin_TGBD;
    private javax.swing.JTable tbSC;
    private com.toedter.calendar.JDateChooser txtNgC;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
