-- TẠO CƠ SỞ DỮ LIỆU --

-- PHẦN I. TỪ CÂU 1 - 10 --
CREATE DATABASE QLBH
USE QLBH

--Cau 1.
CREATE TABLE KHACHHANG
(
	MAKH CHAR(4) CONSTRAINT PK_KH PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	DOANHSO MONEY,
	NGDK SMALLDATETIME,
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(4) CONSTRAINT PK_NV PRIMARY KEY,
	HOTEN VARCHAR(40),
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
)

CREATE TABLE SANPHAM
(
	MASP CHAR(4) CONSTRAINT PK_SP PRIMARY KEY,
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
)

CREATE TABLE HOADON
(
	SOHD INT CONSTRAINT PK_HD PRIMARY KEY,
	NGAYHD SMALLDATETIME,
	MAKH CHAR(4) CONSTRAINT FK_HD_KH FOREIGN KEY REFERENCES KHACHHANG(MAKH),
	MANV CHAR(4) CONSTRAINT FK_HD_NV FOREIGN KEY REFERENCES NHANVIEN(MANV),
	TRIGIA MONEY,
)

CREATE TABLE CTHD
(
	SOHD INT CONSTRAINT FK_CTHD_HD FOREIGN KEY REFERENCES HOADON(SOHD),
	MASP CHAR(4) CONSTRAINT FK_CTHD_SP FOREIGN KEY REFERENCES SANPHAM(MASP),
	SL INT,
	CONSTRAINT PK_CTHD PRIMARY KEY(SOHD, MASP),
)

--Cau 2.
ALTER TABLE SANPHAM
ADD GHICHU VARCHAR(20)

--Cau 3.
ALTER TABLE KHACHHANG 
ADD LOAIKH TINYINT

--Cau 4.
ALTER TABLE SANPHAM
ALTER COLUMN GHICHU VARCHAR(100)

--Cau 5.
ALTER TABLE SANPHAM
DROP COLUMN GHICHU

--Cau 6.
ALTER TABLE KHACHHANG
ALTER COLUMN LOAIKH VARCHAR(20)

--Cau 7.
ALTER TABLE SANPHAM
ADD CHECK (DVT IN ('cay', 'hop', 'cai', 'quyen', 'chuc'))

--Cau 8. 
ALTER TABLE SANPHAM
ADD CHECK (GIA >= 500)

--Cau 9.
ALTER TABLE CTHD
ADD CHECK (SL >= 1)

--Cau 10.
ALTER TABLE KHACHHANG
ADD CHECK (NGDK > NGSINH)



