--PHẦN II. Cau 1 - 8 --
CREATE DATABASE QLGV
USE QLGV

--Cau 1.
CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) CONSTRAINT PK_HV PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
)

CREATE TABLE LOP
(
	MALOP CHAR(3) CONSTRAINT PK_LP PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
)

CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) CONSTRAINT PK_KHOA PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4),
)

CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) CONSTRAINT PK_MH PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA  VARCHAR(4),
)

CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	CONSTRAINT PK_DK PRIMARY KEY(MAMH,MAMH_TRUOC),
)

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) CONSTRAINT PK_GIAOVIEN PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3),
	NGSINH SMALLDATETIME,
	NGVL SMALLDATETIME,
	HESO NUMERIC(4,2),
	MUCLUONG MONEY,
	MAKHOA VARCHAR(4)
)

CREATE TABLE GIANGDAY
(
	MALOP CHAR(3) CONSTRAINT FK_GD_LP FOREIGN KEY REFERENCES LOP(MALOP),
	MAMH VARCHAR(10) CONSTRAINT FK_GD_MH FOREIGN KEY REFERENCES MONHOC(MAMH),
	MAGV CHAR(4) CONSTRAINT FK_GD_GV FOREIGN KEY REFERENCES GIAOVIEN(MAGV),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	CONSTRAINT PK_GIANGDAY PRIMARY KEY(MALOP,MAMH),
)

CREATE TABLE KETQUATHI
(
	MAHV CHAR(5) CONSTRAINT FK_KQTHI_HV FOREIGN KEY REFERENCES HOCVIEN(MAHV),
	MAMH VARCHAR(10) CONSTRAINT FK_KQTHI_MH FOREIGN KEY REFERENCES MONHOC(MAMH),
	LANTHI TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),
	CONSTRAINT PK_KQTHI PRIMARY KEY(MAHV,MAMH, LANTHI),
)

ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DK_MH FOREIGN KEY (MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE MONHOC
ADD CONSTRAINT FK_MH_KHOA FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GV FOREIGN KEY (TRGKHOA) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GV FOREIGN KEY(MAGVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HV_LP FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

--Câu 1. Thêm 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(255),
    DIEMTB FLOAT,
    XEPLOAI VARCHAR(50);

--Câu 2. Đã được định nghĩa
